<?php
/**
 * Single Post Template
 *
 * Displays single posts
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

get_header(); ?>
	<div id="content-full" class="content-area">
			<main id="main" class="site-main full-width" role="main">

				<?php get_template_part( 'template-parts/loop-header' ); ?>

				<?php while ( have_posts() ) : the_post(); ?>

					<?php get_template_part( 'template-parts/content', 'collezione' ); ?>

					<?php // responsive_mobile_post_nav(); ?>
					<?php
					$pagelist = get_posts([
						'post_type' => 'collezione',
						'orderby' => 'title',
						'order' => 'asc',
						'numberposts' => -1,
					]);
					$pages = array();
					foreach ($pagelist as $page) {
					   $pages[] += $page->ID;
					}

					$current = array_search(get_the_ID(), $pages);
					$prevID = $pages[$current-1];
					$nextID = $pages[$current+1];
					?>
					<nav class="navigation post-navigation" role="navigation">
						<h1 class="screen-reader-text"><?php _e( 'Post navigation', 'responsive-mobile' ); ?></h1>

						<div class="nav-links">

							<div class="nav-previous"><?php
								if (!empty($prevID)) {
									echo '<div class="alignleft">';
									echo '<a href="';
									echo get_permalink($prevID);
									echo '"';
									echo 'title="';
									echo get_the_title($prevID);
									echo'">'. get_the_title($prevID) .'</a>';
									echo "</div>";
								}
 							?></div>
							<div class="nav-next"><?php
								if (!empty($nextID)) {
									echo '<div class="alignright">';
									echo '<a href="';
									echo get_permalink($nextID);
									echo '"';
									echo 'title="';
									echo get_the_title($nextID);
									echo'">' . get_the_title($nextID) . '</a>';
									echo "</div>";
								}
							 ?></div>
						</div>
						<!-- .nav-links -->
					</nav><!-- .navigation -->

					<?php responsive_mobile_comments_before(); ?>
					<?php
						// If comments are open or we have at least one comment, load up the comment template
						if ( comments_open() || '0' != get_comments_number() ) :
							comments_template( '', true );
						endif;
					?>
					<?php responsive_mobile_comments_after(); ?>

				<?php endwhile; // end of the loop. ?>

			</main><!-- #main -->

			<?php // get_sidebar(); ?>
	</div><!-- #content -->

<?php get_footer(); ?>
